package utils

import (
	"bufio"
	"regexp"
)

var codegenFiles = make(map[string]bool)
var noCodegenFiles = make(map[string]bool)

func IsCodegen(filePath string) bool {
	if _, exist := codegenFiles[filePath]; exist {
		return true
	}
	if _, exist := noCodegenFiles[filePath]; exist {
		return false
	}

	firstLine := ""
	ReadFileByScanner(filePath, func(scanner *bufio.Scanner) {
		if scanner.Scan() {
			firstLine = scanner.Text()
		}
	})

	if IsCodegenLine(firstLine) {
		codegenFiles[filePath] = true
		return true
	} else {
		noCodegenFiles[filePath] = true
		return false
	}
}

var codegenMatch = regexp.MustCompile(`// Code generated by .* DO NOT EDIT`)

func IsCodegenLine(line string) bool {
	return codegenMatch.MatchString(line)
}
